#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-logger
Version  : 0.4.0
Release  : 16
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/logger_0.4.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/logger_0.4.0.tar.gz
Summary  : A Lightweight, Modern and Flexible Logging Utility
Group    : Development/Tools
License  : MIT
BuildRequires : R-devtools
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Python module, this utility provides a flexible and extensible way of
    formatting and delivering log messages with low overhead.

%prep
%setup -q -n logger
pushd ..
cp -a logger buildavx2
popd
pushd ..
cp -a logger buildavx512
popd
pushd ..
cp -a logger buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731644666

%install
export SOURCE_DATE_EPOCH=1731644666
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/logger/DESCRIPTION
/usr/lib64/R/library/logger/INDEX
/usr/lib64/R/library/logger/LICENSE
/usr/lib64/R/library/logger/Meta/Rd.rds
/usr/lib64/R/library/logger/Meta/features.rds
/usr/lib64/R/library/logger/Meta/hsearch.rds
/usr/lib64/R/library/logger/Meta/links.rds
/usr/lib64/R/library/logger/Meta/nsInfo.rds
/usr/lib64/R/library/logger/Meta/package.rds
/usr/lib64/R/library/logger/Meta/vignette.rds
/usr/lib64/R/library/logger/NAMESPACE
/usr/lib64/R/library/logger/NEWS.md
/usr/lib64/R/library/logger/R/logger
/usr/lib64/R/library/logger/R/logger.rdb
/usr/lib64/R/library/logger/R/logger.rdx
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/DESCRIPTION
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/LICENSE
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/NAMESPACE
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/R/tester.R
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/man/logger_info_tester_function.Rd
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/man/logger_tester_function.Rd
/usr/lib64/R/library/logger/doc/Intro.R
/usr/lib64/R/library/logger/doc/Intro.Rmd
/usr/lib64/R/library/logger/doc/Intro.html
/usr/lib64/R/library/logger/doc/anatomy.R
/usr/lib64/R/library/logger/doc/anatomy.Rmd
/usr/lib64/R/library/logger/doc/anatomy.html
/usr/lib64/R/library/logger/doc/customize_logger.R
/usr/lib64/R/library/logger/doc/customize_logger.Rmd
/usr/lib64/R/library/logger/doc/customize_logger.html
/usr/lib64/R/library/logger/doc/index.html
/usr/lib64/R/library/logger/doc/migration.R
/usr/lib64/R/library/logger/doc/migration.Rmd
/usr/lib64/R/library/logger/doc/migration.html
/usr/lib64/R/library/logger/doc/performance.R
/usr/lib64/R/library/logger/doc/performance.Rmd
/usr/lib64/R/library/logger/doc/performance.html
/usr/lib64/R/library/logger/doc/r_packages.R
/usr/lib64/R/library/logger/doc/r_packages.Rmd
/usr/lib64/R/library/logger/doc/r_packages.html
/usr/lib64/R/library/logger/doc/write_custom_extensions.R
/usr/lib64/R/library/logger/doc/write_custom_extensions.Rmd
/usr/lib64/R/library/logger/doc/write_custom_extensions.html
/usr/lib64/R/library/logger/help/AnIndex
/usr/lib64/R/library/logger/help/aliases.rds
/usr/lib64/R/library/logger/help/figures/colors.png
/usr/lib64/R/library/logger/help/figures/logo.png
/usr/lib64/R/library/logger/help/logger.rdb
/usr/lib64/R/library/logger/help/logger.rdx
/usr/lib64/R/library/logger/help/paths.rds
/usr/lib64/R/library/logger/html/00Index.html
/usr/lib64/R/library/logger/html/R.css
/usr/lib64/R/library/logger/tests/testthat.R
/usr/lib64/R/library/logger/tests/testthat/_snaps/formatters.md
/usr/lib64/R/library/logger/tests/testthat/_snaps/helpers.md
/usr/lib64/R/library/logger/tests/testthat/_snaps/hooks.md
/usr/lib64/R/library/logger/tests/testthat/_snaps/layouts.md
/usr/lib64/R/library/logger/tests/testthat/_snaps/logger.md
/usr/lib64/R/library/logger/tests/testthat/_snaps/try.md
/usr/lib64/R/library/logger/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/logger/tests/testthat/helper.R
/usr/lib64/R/library/logger/tests/testthat/test-appenders.R
/usr/lib64/R/library/logger/tests/testthat/test-eval.R
/usr/lib64/R/library/logger/tests/testthat/test-formatters.R
/usr/lib64/R/library/logger/tests/testthat/test-helpers.R
/usr/lib64/R/library/logger/tests/testthat/test-hooks.R
/usr/lib64/R/library/logger/tests/testthat/test-layouts.R
/usr/lib64/R/library/logger/tests/testthat/test-logger-meta.R
/usr/lib64/R/library/logger/tests/testthat/test-logger.R
/usr/lib64/R/library/logger/tests/testthat/test-return.R
/usr/lib64/R/library/logger/tests/testthat/test-try.R
/usr/lib64/R/library/logger/tests/testthat/test-utils.R
