#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: 1ab68ca
#
Name     : R-logger
Version  : 0.3.0
Release  : 15
URL      : https://cran.r-project.org/src/contrib/logger_0.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/logger_0.3.0.tar.gz
Summary  : A Lightweight, Modern and Flexible Logging Utility
Group    : Development/Tools
License  : AGPL-3.0
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# logger
[![Project Status: Active – The project has reached a stable, usable state and is being actively developed.](https://www.repostatus.org/badges/latest/active.svg)](https://www.repostatus.org/#active) [![CRAN](https://www.r-pkg.org/badges/version/logger)](https://cran.r-project.org/package=logger) [![Build Status](https://github.com/daroczig/logger/workflows/R-CMD-check/badge.svg)](https://github.com/daroczig/logger/actions) [![Code Coverage](https://codecov.io/gh/daroczig/logger/branch/master/graph/badge.svg)](https://app.codecov.io/gh/daroczig/logger) [![A Mikata Project](https://mikata.dev/img/badge.svg)](https://mikata.dev)

%prep
%setup -q -n logger
pushd ..
cp -a logger buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709742295

%install
export SOURCE_DATE_EPOCH=1709742295
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/logger/DESCRIPTION
/usr/lib64/R/library/logger/INDEX
/usr/lib64/R/library/logger/Meta/Rd.rds
/usr/lib64/R/library/logger/Meta/demo.rds
/usr/lib64/R/library/logger/Meta/features.rds
/usr/lib64/R/library/logger/Meta/hsearch.rds
/usr/lib64/R/library/logger/Meta/links.rds
/usr/lib64/R/library/logger/Meta/nsInfo.rds
/usr/lib64/R/library/logger/Meta/package.rds
/usr/lib64/R/library/logger/Meta/vignette.rds
/usr/lib64/R/library/logger/NAMESPACE
/usr/lib64/R/library/logger/NEWS.md
/usr/lib64/R/library/logger/R/logger
/usr/lib64/R/library/logger/R/logger.rdb
/usr/lib64/R/library/logger/R/logger.rdx
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/DESCRIPTION
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/NAMESPACE
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/R/tester.R
/usr/lib64/R/library/logger/demo-packages/logger-tester-package/man/logger_tester_function.Rd
/usr/lib64/R/library/logger/demo/colors.R
/usr/lib64/R/library/logger/doc/Intro.R
/usr/lib64/R/library/logger/doc/Intro.Rmd
/usr/lib64/R/library/logger/doc/Intro.html
/usr/lib64/R/library/logger/doc/anatomy.R
/usr/lib64/R/library/logger/doc/anatomy.Rmd
/usr/lib64/R/library/logger/doc/anatomy.html
/usr/lib64/R/library/logger/doc/customize_logger.R
/usr/lib64/R/library/logger/doc/customize_logger.Rmd
/usr/lib64/R/library/logger/doc/customize_logger.html
/usr/lib64/R/library/logger/doc/index.html
/usr/lib64/R/library/logger/doc/migration.R
/usr/lib64/R/library/logger/doc/migration.Rmd
/usr/lib64/R/library/logger/doc/migration.html
/usr/lib64/R/library/logger/doc/performance.Rmd
/usr/lib64/R/library/logger/doc/performance.html
/usr/lib64/R/library/logger/doc/r_packages.R
/usr/lib64/R/library/logger/doc/r_packages.Rmd
/usr/lib64/R/library/logger/doc/r_packages.html
/usr/lib64/R/library/logger/doc/write_custom_extensions.R
/usr/lib64/R/library/logger/doc/write_custom_extensions.Rmd
/usr/lib64/R/library/logger/doc/write_custom_extensions.html
/usr/lib64/R/library/logger/help/AnIndex
/usr/lib64/R/library/logger/help/aliases.rds
/usr/lib64/R/library/logger/help/figures/colors.png
/usr/lib64/R/library/logger/help/logger.rdb
/usr/lib64/R/library/logger/help/logger.rdx
/usr/lib64/R/library/logger/help/paths.rds
/usr/lib64/R/library/logger/html/00Index.html
/usr/lib64/R/library/logger/html/R.css
/usr/lib64/R/library/logger/load-packages-in-background-process.R
/usr/lib64/R/library/logger/tests/testthat.R
/usr/lib64/R/library/logger/tests/testthat/test-CRANSKIP-appenders.R
/usr/lib64/R/library/logger/tests/testthat/test-CRANSKIP-helpers.R
/usr/lib64/R/library/logger/tests/testthat/test-CRANSKIP-hooks.R
/usr/lib64/R/library/logger/tests/testthat/test-CRANSKIP-logger-namespaces.R
/usr/lib64/R/library/logger/tests/testthat/test-appender.R
/usr/lib64/R/library/logger/tests/testthat/test-eval.R
/usr/lib64/R/library/logger/tests/testthat/test-formatters.R
/usr/lib64/R/library/logger/tests/testthat/test-helpers.R
/usr/lib64/R/library/logger/tests/testthat/test-layout.R
/usr/lib64/R/library/logger/tests/testthat/test-logger.R
/usr/lib64/R/library/logger/tests/testthat/test-return.R
/usr/lib64/R/library/logger/tests/testthat/test-utils.R
